CLA cleanup, add simple CLA to contributing.md and PR template
flashbots/mev-boost-relay pull request #97
Opened 2022-08-31 08:26 UTC by metachris

## 📝 Summary

Using a simple CLA as part of `CONTRIBUTING.md` and a checkbox on PR templates

---

## ✅ I have run these commands

* [x] `make lint`
* [x] `make test-race`
* [x] `go mod tidy`

2022-08-31 16:24 UTC, come-maiz commented
ok, I like this better :) We need to attribute the text to google. Which I think would be enough to do it in this pull request. Or maybe in the contributing.md itself, say thanks to Google.

2022-09-01 00:10 UTC, come-maiz requested changes

2022-09-01 00:10 UTC, come-maiz commented on CONTRIBUTING.md
> +
```suggestion

This text is copied from Google's contributors license agreement: 
https://cla.developers.google.com/about/google-individual

```

2022-09-01 14:50 UTC, bertmiller approved these changes
lgtm

2022-09-01 16:56 UTC, come-maiz approved these changes

2022-09-01 19:40 UTC, merged